### ISSUE TITLE
NFR1 Hash and salt password before storing into database

### ISSUE THREAD

**Issue by KengXIII** [CS3219-AY2223S1/cs3219-project-ay2223s1-g49#11]
NFR1 (Users' passwords should be hashed and salted before storing in the DB.)

- [X] Use Bcrypt package to generate salt and hash user's password
- [X] Passwords are salted and hashed before saving to database
- [X] Passwords are hashed and compared with the stored password

**Comment by alexteo98** [comment]
Resolved by #12
